on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dep
        run: |
          sudo apt update
          sudo apt install llvm -y
          sudo apt install gcc-multilib -y
          sudo apt install libbpf-dev -y
          sudo apt install linux-libc-dev -y
          sudo apt install linux-headers-$(uname -r) -y
          sudo find /usr -name "unaligned.h"

      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Generate
        run: |
          go generate ./...

      - name: Build
        run: |
          CGO_ENABLED=0 go build --ldflags '-s -w -extldflags "-static -fpic"' -o flat cmd/flat.go

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: flat
          path: flat